INSERT INTO `questions` (`id`,`quizId`,`text`) VALUES
(480,2,'La distancia media entre la Tierra y el Sol es de 149 600 000 km, esta cantidad expresada en notación científica es'),
(481,2,'El diámetro de un electrón del orden de 0,000 000 000 000 000 8 m, esta cantidad expresada en notación científica es'),
(482,2,'El resultado de 5 elevado a 0 es siempre:'),
(483,2,'Operaciones con potencia 65 *62 es igual a:'),
(484,2,'Operaciones con potencia 88*82 es igual a:'),
(485,2,'Operaciones con potencia 1010 *1010 es igual a:'),
(486,2,'Operaciones con potencia (73)4 es igual a:'),
(487,2,'Operaciones con potencia (125)5 es igual a:'),
(488,2,'Operaciones con potencia (172)10 es igual a:'),
(489,2,'Sobre un trineo de 90 kg de masa, inicialmente en reposo, se aplica una fuerza constante de 180 N , aplicamos la ley fundamental de la dinámica para determinar la aceleración, si m=90; F=180N; y F=m*a'),
(490,2,'Transforma energía eléctrica en calor, tipo de receptor'),
(491,2,'Fuente de energía no renovable.'),
(492,2,'Fuente de energía renovable.'),
(493,2,'Es el volumen acústico con que se percibe un sonido y corresponde a la amplitud de la onda sonora.'),
(494,2,'La luz es capaz de estimular el sentido de:'),
(495,2,'Según el sistema internacional de unidades, la unidad para la magnitud de masa.'),
(496,2,'Sistema de tres ejes de coordenadas, OX,OY y OZ.'),
(497,2,'Sistema de dos ejes de coordenadas, OX y OY'),
(498,2,'Sistema de un eje de coordenada, OX.'),
(499,2,'En la potencia dos a la sexta , el resultado es:'),
(500,2,'En la potencia 5 a la 3 , el resultado es:'),
(501,2,'En la potencia 3 a la 4 , el resultado es:'),
(502,2,'Cuale es el resultado de: -(32)2'),
(503,2,'Cuale es el resultado de: -(-24)1'),
(504,2,'De la multiplicación 4 x (6+1), marque la alternativa que corresponde a la propiedad distributiva de la multiplicación:'),
(505,2,'De la multiplicación 1y (9+10), marque la alternativa que corresponde a la propiedad distributiva de la multiplicación:'),
(506,2,'Determine la mediana en la siguiente muestra: 11, 14, 17, 10'),
(507,2,'Determine la mediana en la siguiente muestra: 14, 15, 16, 19,20'),
(508,2,'Determine la mediana en la siguiente muestra: 5, 6, 7, 8'),
(509,2,'Determine la media en la siguiente muestra: 4, 1, 6, 14'),
(510,2,'Determine la media en la siguiente muestra: 6, 6, 6, 6,6'),
(511,2,'¿Cuánto es el 17% de 22?'),
(512,2,'Cuánto es el 20% de 320?'),
(513,2,'¿Cuánto es el 1% de 0.1?'),
(514,2,'De la siguiente expresión: 3 x 2 – 4 x 3 -2 (-10). Indique cuál es su resultado:'),
(515,2,'De la siguiente expresión: 10 x(- 2) – 10 x 3 -10 (-10). Indique cuál es su resultado:'),
(516,2,'De la siguiente expresión: 3 x 10 – 4 x 10 -2 (-10). Indique cuál es su resultado:'),
(517,2,'La unidad de medida de la superficie en el Sistema Internacional de medida es:'),
(518,2,'Un kilómetro cuadrado es:'),
(519,2,'A todo número, diferente de uno y de cero, que es divisible sólo por sí mismo y por la unidad, se le llama:'),
(520,2,'Representar la fracción nueve séptimos:'),
(521,2,'Cuál es el resultado de -5(1) +(-5) +(7)'),
(522,2,'Cuál es el resultado de -100-(-100).10+10'),
(523,2,'Cálculo mental rápido: cuánto es 80(0)+80'),
(524,2,'Cálculo mental rápido: cuánto es 18*1+18-9*2'),
(525,2,'Cálculo mental rápido: cuánto es 100+101'),
(526,2,'Seleccione los números que continúan en la secuencia:400- 40=360+80=440-40=X+80='),
(527,2,'Seleccione el número que continúan en la secuencia: 4:8:24:96:480: ……..'),
(528,2,'Seleccione los números que continúan en la secuencia: 3:18:9:34:27: 50:……:……'),
(529,2,'Seleccione los números que continúan en la secuencia: 1:4:9:16:25:….'),
(530,2,' Seleccione los números que continúan en la secuencia: 54:48:43:39:….'),
(531,2,'Cero dividido entre cualquier número siempre da …..'),
(532,2,'Los elementos de la división son: Dividendo, Divisor, Resto,…….'),
(533,2,'la composición del número 89 es:'),
(534,2,' 30 mas la raíz cuadrada de (-5)2'),
(535,2,'Los perímetros tienen dimensiones de :'),
(536,2,'Las áreas tienen dimensiones de:'),
(537,2,'Los triángulos rectángulos son aquellos que contienen un ángulo de :'),
(538,2,'Los lados de este triangulo de 90° se llaman catetos, mientras que el tercer lado recibe el nombre de.'),
(539,2,'El teorema de Pitágoras establece que la suma de los cuadrados de los dos catetos es igual al cuadrado de la hipotenusa:'),
(540,2,'Un cuerpo está en movimiento si cambia de posición con respecto al sistema de referencia; en caso contrario, decimos que está en:'),
(541,2,'La aceleración de un móvil representa la rapidez con que varía su:'),
(542,2,'A pequeñas distancias de la superficie terrestre podemos suponer que g (gravedad) es constante e igual a …..'),
(543,2,'La primera ley de Newton.'),
(544,2,'la segunda ley de Newton:'),
(545,2,'La propiedad de la materia de no poder cambiar su estado de reposo o de movimiento por sí misma recibe el nombre de:'),
(546,2,'Un newton es la fuerza que debe aplicarse a un cuerpo de un kilogramo de masa para que incremente su velocidad 1 m/s2 cada segundo, es decir:'),
(547,2,'Al iniciar una carrera, una nadadora aplica una fuerza contra la pared. La nadadora recibe una fuerza de la pared que la impulsa hacia delante.'),
(548,2,'Las fuentes de energía renovables son aquellas que pueden considerarse ….'),
(549,2,'Escala de temperatura:'),
(550,2,'Fenómenos más importantes de la naturaleza cuya transmisión tiene lugar mediante las ondas.'),
(551,2,'Según el sistema internacional de unidades, la unidad para la magnitud de tiempo es:'),
(552,2,'El movimiento circular es aquel movimiento cuya trayectoria es una:'),
(553,2,'Al dividir 180 entre 4 da como resultado:'),
(554,2,'Al dividir 20 entre 20 da como resultado:'),
(555,2,'Al dividir 100 entre 2 da como resultado:'),
(556,2,'Al dividir 80 entre 4 da como resultado:'),
(557,2,'Al dividir 125 entre 5 da como resultado'),
(558,2,'El resultado de la suma 7.459 + 7.784 es igual a :'),
(559,2,'El resultado de la suma 252 + 352 es igual a :'),
(560,2,'El resultado de la suma 1.995 + 1.995 es igual a'),
(561,2,'El resultado de la suma 5.19 + 51.9 es igual a'),
(562,2,'El resultado de la suma 12.468 + 468.12 es igual a'),
(563,2,'El resultado de la multiplicación 1 x 0 es igual a:'),
(564,2,'El resultado de la multiplicación 11x 11 es igual a'),
(565,2,'El resultado de la multiplicación 8 x 0.8 es igual a :'),
(566,2,'El resultado de la multiplicación 0.06 x 10 es igual a'),
(567,2,'El resultado de la multiplicación 6 x 6.0 es igual a :'),
(568,2,'El resultado de la multiplicación 9.0 x 9.0 es igual a'),
(569,2,'Los 2/4 de 40 es igual a'),
(570,2,'EL 1/2 de es 50.5 igual a'),
(571,2,'Una hora tiene'),
(572,2,'El numero 0 cero pertenece a los números'),
(573,2,'8, 16, 24 son Múltiplos de :'),
(574,2,'El número posterior a 9000 es el'),
(575,2,'Dos ángulos son complementarios si suman'),
(576,2,'En la potencia 4 al cuadrado:'),
(577,2,'En la potencia 5 a la sexta :'),
(578,2,'En la potencia 6 a la octava:'),
(579,2,'En la potencia 2 a la quinta.'),
(580,2,'En la sucesión 3, 8, 13, 18, 23, 28, ..}'),
(581,2,'Los números enteros 15, 25, 35 suman'),
(582,2,'La jerarquía de operaciones se refiere al orden en que se deben realizar'),
(583,2,'Al dividir 82 entre 2 da como resultado'),
(584,2,'Dos ángulos son suplementarios si suman:'),
(585,2,'El triángulo que tiene dos lados iguales y uno desigual se llama'),
(586,2,'El 20% de 525 es igual a'),
(587,2,'El 24% de 150 es'),
(588,2,'Los triángulos por sus ángulos se clasifican en:'),
(589,2,'Los triángulos por sus lados se clasifican en:'),
(590,2,'54 al cuadrado es'),
(591,2,'33 al cubo tenemos como resultado'),
(592,2,'Un ángulo llano mide'),
(593,2,'El valor de X en la siguiente ecuación 20x = 10x . 50 es igual a:'),
(594,2,'El valor de Y en la siguiente ecuación 5y = 8y-15 es igual a'),
(595,2,'Un triángulo es escaleno cuando:'),
(596,2,'Las partes de una fracción es el'),
(597,2,'Los elementos básicos de la estadística son:'),
(598,2,'La cantidad que expresa el número romano XV es:'),
(599,2,'La cantidad que expresa el número romano XIII es :'),
(600,2,'Si se divide 98 entre 7 tenemos como resultado:'),
(601,2,'El número anterior a 2000 es el'),
(602,2,'Una división entera es aquella en la que el resto es'),
(603,2,'El rectángulo tiene'),
(604,2,'Los elementos de la división son:'),
(605,2,'Los elementos del plano cartesiano son:'),
(606,2,'El 100% de 50 es igual a'),
(607,2,'El 15% de 3000 es igual a'),
(608,2,'Un ángulo completo mide:'),
(609,2,'Un par ordenado está conformado por'),
(610,2,'El valor de X en la siguiente ecuación 10x = 8x + 6'),
(611,2,'Un hectómetro es igual a'),
(612,2,'El trinomio x2 -8x + 16 es igual a'),
(613,2,'La raíz cuadrada de 81/9 es'),
(614,2,'La unidad de medida en el Sistema Internacional de Unidades (SI) de la masa es:'),
(615,2,'La edad de A y B suma 20 años. Si la edad de B es 3 veces la edad de A, A tiene:'),
(616,2,'La edad de A y B suma 20 años. Si la edad de B es 3 veces la edad de A, B tiene'),
(617,2,'Polinomio es una expresión algebraica que consta más de:'),
(618,2,' 23457ab2-23457ab2 la respuesta es'),
(619,2,'Valor numérico para 3a√2bc, Si a = 4, b=2 y c=4'),
(620,2,'En	resta algebraica, -8 restar 8 es igual a'),
(621,2,'El día de 5 de abril Laura compró 542 cuentos infantiles y hoy compró 333 para su hermana. ¿Cuántos cuentos infantiles compró entre los dos días?'),
(622,2,'Luis es dueño de un concesionario de vehículos y acaba de adquirir 850 nuevos vehículos de los cuales en la tarde vende 51. ¿Cuántos vehículos tiene actualmente?'),
(623,2,'Escoja la respuesta correcta en la siguiente ley de signos: - por –'),
(624,2,'Escoja la respuesta correcta en la siguiente ley de signos: - por +'),
(625,2,'Simplifique la siguiente expresión algebraica: 4x³ - 2x² + 10x³ - 5x² - 4x + 6'),
(626,2,'Si una bicicleta se desplaza a 30 km/h durante 20 minutos y luego a 60 km/h durante 30 minutos, ¿cuántos kilómetros recorrerá durante su trayecto?'),
(627,2,'Hallar el valor de la siguiente fracción: 30 / (6/1)'),
(628,2,'La medida alrededor de una figura de dos dimensiones, se llama:'),
(629,2,'La unidad de la fuerza en el sistema internacional de medidas es:'),
(630,2,'Representar la fracción diez tercios :'),
(631,2,'Cuál es el resultado de -5(5) +(-2) +(10)'),
(632,2,'Cuál es el resultado de -90-(-89).10+1'),
(633,2,'Cálculo mental rápido: cuánto es 160(0)+10'),
(634,2,'Cálculo mental rápido: cuánto es 88*1+1-9*9'),
(635,2,'Cálculo mental rápido: cuánto es 100+102'),
(636,2,'Seleccione los números que continúan en la secuencia:40- 30=10+90=100-30=X+90='),
(637,2,'Seleccione los números que continúan en la secuencia: 3:6:18:72:360: ……..'),
(638,2,'Seleccione los números que continúan en la secuencia: 2:16:4:32:8: 48:……:……'),
(639,2,'Seleccione el número que continúan en la secuencia: 2:5:10:17: 26:….'),
(640,2,'Seleccione los números que continúan en la secuencia: 84: 78:73:69:….'),
(641,2,'uno dividido entre uno siempre da …..'),
(642,2,'Los elementos de la multiplicación son: multiplicando, multiplicador,'),
(643,2,'la composición del número 39 es:'),
(644,2,'90 más la raíz cuadrada de (-3)2'),
(645,2,'Los perímetros tienen dimensiones de :'),
(646,2,'Las áreas tienen dimensiones de:'),
(647,2,'Los triángulos obtusángulos son aquellos que contienen un ángulo'),
(648,2,'Los lados de este triángulo de 90° se llaman catetos, mientras que el tercer lado recibe el nombre de.'),
(649,2,'El teorema de Pitágoras establece que la suma de los cuadrados de los dos catetos es igual al cuadrado de la hipotenusa:'),


INSERT INTO `questions` (`id`,`quizId`,`text`) VALUES
(650,3,'Is the ocean salty?'),
(651,3,'Is a cat a type of fish?'),
(652,3,'Are rocks soft?'),
(653,3,'Are all fruits sweet?'),
(654,3,'Do fish live in wáter?'),
(655,3,'Is ice hot?'),
(656,3,'is the word “lazy” a verb?'),
(657,3,'Is the word “jump” a verb?'),
(658,3,'Is the plural of train"trainers"?'),
(659,3,'Does the English word “January” means enero?'),
(660,3,'Does the English word “Monday” mean lunes?'),
(661,3,'Does the English word “Human Rights” mean Derechos humanos?'),
(662,3,'Does the English word “Steal” mean robar?'),
(663,3,'Does the English word “Police report” mean parte Policial?'),
(664,3,'Does the English word “Citizen security” mean Seguridad Ciudadana?'),
(665,3,'is December a month of the year?'),
(666,3,'is Tuesday a month of the year?'),
(667,3,'Is grass green?'),
(668,3,'The plural of book is "books"'),
(669,3,'The plural of bus is "buses"'),
(670,3,'The singular of cities is "citi"'),
(671,3,'The plural of box is "boxes"'),
(672,3,'The singular of guys is "guy"'),
(673,3,'"Amarillo"in English is “purple”'),
(674,3,'"Naranja"in English is violet'),
(675,3,'"Negro"in English is White'),
(676,3,'The singular of heroes is "hero"'),
(677,3,'The plural of lion is "lyons"'),
(678,3,'The plural of police man is "police men"'),
(679,3,'The plural of thief is "thieves"'),
(680,3,'The singular of countries is "country"'),
(681,3,'The singular of fishers is "fishes"'),
(682,3,'The plural of carrot is "carrottes"'),
(683,3,'The plural of child is "children"'),
(684,3,'The singular of feet is "fut"'),
(685,3,'"Goose"in English is gray'),
(686,3,'"Azul"in English is blue'),
(687,3,'"Negro"in English is brown'),
(688,3,'"Morado"in English is red'),
(689,3,'"Blanco"in English is pink'),
(690,3,'"Azul"in English is green'),
(691,3,'The cardinal number 81 is written (eighteen)'),
(692,3,'The cardinal number 17 is written (seventeen)'),
(693,3,'The cardinal number 11 is written (eleven)'),
(694,3,'The cardinal number 41 is written (forty six)'),
(695,3,'The possessive adjective of (I) is (mine)'),
(696,3,'The possessive adjective of (you) is (your)'),
(697,3,'The possessive adjective of (he) is (him)'),
(698,3,'The possessive adjective of (she) is (shis)'),
(699,3,'“Car” and “vehicle” are synonyms.'),
(700,3,'The word “rain” is an adjective.'),
(701,3,'House” is a synonym for “home.'),
(702,3,'The opposite of “cold” is “hot.”'),
(703,3,'The word “run” is a verb.'),
(704,3,'“Blue” is a noun'),
(705,3,'The word “elephant” starts with a vowel.'),
(706,3,'There are 6 days in a week.'),
(707,3,'Birds have wings and can fly.'),
(708,3,'Humans need food and water to survive.'),
(709,3,'Bananas grow on trees.'),
(710,3,'Cars can float on water like boats.'),
(711,3,'Dinosaurs are still alive today'),
(712,3,'The Earth is round'),
(713,3,'All butterflies are colorful.'),
(714,3,'Elephants can fly'),
(715,3,'All fruits are sweet'),
(716,3,'Cars can swim'),
(717,3,'The sky is blue.'),
(718,3,'Tigers are herbivores'),
(719,3,'All vegetables are green'),
(720,3,'All clouds are made of water vapor'),
(721,3,'The cardinal number 37 is written (thirty seven)'),
(722,3,'The cardinal number 21 is written (twenty)'),
(723,3,'The cardinal number 94 is written (ninety four)'),
(724,3,'The cardinal number 63 is written (sixty three)'),
(725,3,'The cardinal number 16 is written (thirteen)'),
(726,3,'The cardinal number 32 is written (thirty twelve)'),
(727,3,'The past participle of the verb (do) is (done)'),
(728,3,'The past participle of the verb (go) is (gone)'),
(729,3,'The past participle of the verb (make) is (made)'),
(730,3,'The past participle of the verb (take) is (thought)'),
(731,3,'The possessive adjective of (we) is (yours)'),
(732,3,'The possessive adjective of (it) is (their)'),
(733,3,'The nationality of Italy is Italian'),
(734,3,'The nationality of Colombia is Columbus'),
(735,3,'The nationality of France is French'),
(736,3,'The nationality of German is Germany'),
(737,3,'The nationality of Spain is Swedish'),
(738,3,'The ordinal number 36th is written (tery six)'),
(739,3,'The ordinal number 48th is written (fifty eight)'),
(740,3,'The ordinal number 23rd is written (thirty third)'),
(741,3,'The ordinal number 70th is written (seventieth)'),
(742,3,'The ordinal number 30th is written (twelfth)'),
(743,3,'The nationality of Poland is Polish'),
(744,3,'The nationality of Sweden is Swedish'),
(745,3,'The nationality of Russia is Russian'),
(746,3,'The nationality of Peru is Peruvian'),
(747,3,'The nationality of Mexico is North Mexico'),
(748,3,'The nationality of Portugal is Portuguese'),
(749,3,'The nationality of Korea is Korean'),
(750,3,'The nationality of Denmark is Danishers'),
(751,3,'Blackboard means Teclado'),
(752,3,'Table means Tabla'),
(753,3,'Gun means Arma'),
(754,3,'Street means Calle'),
(755,3,'Uniform means Unico'),
(756,3,'The past simple of the verb (become) is (became)'),
(757,3,'The past simple of the verb (bring) is (broken)'),
(758,3,'The past simple of the verb (advance) is (advanced)'),
(759,3,'The past simple of the verb (eat) is (ate)'),
(760,3,'The past simple of the verb (paint) is (painted)'),
(761,3,'The past simple of the verb (smell) is (smelled)'),
(762,3,'The past simple of the verb (wake) is (wakened)'),
(763,3,'The eyes of a person are located in the chest'),
(764,3,'The lashes of a person are located in the face'),
(765,3,'The lip of a person is located in the mouth'),
(766,3,'Planet earth is in the lunar system'),
(767,3,'The hair of a person is located on the feet'),
(768,3,'Marco is from Ambato'),
(769,3,'Marisol are a doctor'),
(770,3,'Lorena and Ruth are friends'),
(771,3,'Charles and Katherine are Police Officers'),
(772,3,'I am a fireman'),
(773,3,'Ines are from Miami'),
(774,3,'Are she at home?"'),
(775,3,'Is Narcisa your sister?"'),
(776,3,'Are Juan and Pedro brothers?'),
(777,3,'Are you mad?'),
(778,3,'Is he old?'),
(779,3,'Are you smart?'),
(780,3,'Are she slim?'),
(781,3,'Are they lazy?'),
(782,3,'Do you smoke every day?'),
(783,3,'Does she usually clean?'),
(784,3,'Does he often run in the mornings?'),
(785,3,'Do he drive to work every day?'),
(786,3,'Do Marco fix the car?'),
(787,3,'Do birds have wings?'),
(788,3,'Do clouds float in the sky?'),
(789,3,'Do trees have leaves?'),
(790,3,'Lucia was walking to school'),
(791,3,'Carolina and Marcia was reading all the day'),
(792,3,'You was walking at school'),
(793,3,'Juan was breaking a book'),
(794,3,'Joel were drinking in the party'),
(795,3,'You was going to the Andean mountain'),
(796,3,'He was taking his new driving classes'),
(797,3,'She was playing with him'),
(798,3,'Rosa were watching video games'),
(799,3,'Tamy and Rose were painting their room'),


(800,3,'Where ______your friends going while you were taking the tests?'),
(801,3,'While we ______my parents were coming back home.'),
(802,3,'My students ______some important tenses some levels ago.'),
(803,3,'The driver was going really fast when he ______into that post.'),
(804,3,'Does your country give ______job sources to people?'),
(805,3,'How ______mice are there in that old house?'),
(806,3,'______has come to visit you today.'),
(807,3,'There isn’t ______applying for that jo'),
(808,3,'Our forefathers ______different kinds of grains daily.'),
(809,3,'Did your boyfriend ______a lot when he was a child?'),
(810,3,'Authorities are discussing ______the dates for the semester.'),
(811,3,'My father agrees ______freedom to all children.'),
(812,3,'Your couple seems ______a big problem.'),
(813,3,'Sometimes, I get bored ______Mexican movies.'),
(814,3,'I am tired ______working so hard.'),

(815,3,"CHOOSE THE CORRECT SENTENCE WRITTEN."),
(816,3,"CHOOSE THE CORRECT SENTENCE WRITTEN."),
(817,3,"CHOOSE THE CORRECT SENTENCE WRITTEN."),
(818,3,"CHOOSE THE CORRECT SENTENCE WRITTEN."),
(819,3,"CHOOSE THE CORRECT SENTENCE WRITTEN."),


(820,3,"Some theories about evolutions are based ______Darwin’s."),
(821,3,"I usually care______what my brother does."),
(822,3,"My mom loves to cook. ______food is delicious."),
(823,3,"If our president ______working well, he ______be reelected."),
(824,3,"If Ecuador______ part in some international organizations, we have good benefits."),
(825,3,"______ has called my brother several times today."),
(826,3,"Women don’t drink ______men."),
(827,3,"Did you ______a lot when you were younger?"),
(828,3,"Parents should enjoy ______with their children."),
(829,3,"My sister is angry ______me."),


(830,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: take it easy"),
(831,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: mother in law"),
(832,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: twins"),
(833,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: widowed"),
(834,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: alike"),
(835,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: both"),
(836,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: awesome"),
(837,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: scenic"),
(838,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: bumpy"),
(839,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: seasick"),
(840,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: to sightsee"),
(841,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: silly"),
(842,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: tube"),
(843,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: weird"),
(844,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: gorgeous"),
(845,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: clay"),
(846,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: fixed by"),
(847,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: bald"),
(848,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: nail file"),
(849,3,"CHOOSE A SYNONYM FOR THE FOLLOWING PHRASE: sleep"),


(850,3,"How old ______your mother?"),
(851,3,"What ______your best friend study at the university?"),
(852,3,"My family ______to the beach every vacation."),
(853,3,"We ______English well."),
(854,3,"My siblings and I have an apartment; ______apartment is in the south of Quito."),
(855,3,"her boyfriend cooks very well, ______food is delicious."),
(856,3,"My parents are ______ responsible people."),
(857,3,"My older brother is an efficient student ______."),
(858,3,"Teenagers are funny ______."),
(859,3,"My dad is not angry ______."),
(860,3,"______ usually protect ______"),
(861,3,"______ is always talking to ______."),
(862,3,"Are ______ preparing ______ soon?"),
(863,3,"What ______ do on Christmas?"),
(864,3,"Are you a careful student?"),
(865,3,"Whose English student are you?"),
(866,3,"What is Quito like?"),



(867,3,"CHOOSE THE CORRECT SENTENCE WRITTEN."),
(868,3,"CHOOSE THE CORRECT SENTENCE WRITTEN."),
(869,3,"CHOOSE THE CORRECT SENTENCE WRITTEN."),
(870,3,"CHOOSE THE CORRECT SENTENCE WRITTEN."),

(871,3,"There are many people ______Spain"),
(872,3,"I met Ruth ______the South Coast."),
(873,3,"his room is ______the second floor."),
(874,3,"The movie is ______8:15."),
(875,3,"What do you do ______weekends?"),
(876,3,"We often go to the beach ______the summer."),
(877,3,"her birthday is ______the 21st of May."),
(878,3,"Dominic's birthday is ______September."),
(879,3,"We are getting married ______the autumn."),
(880,3,"My birthday is ______June."),
(881,3,"______you happy?"),
(882,3,"Carlos and Geovanna ______at home. (Negative)"),
(883,3,"Christian and Lucia ______baseball players."),
(884,3,"My cat ______in my room."),
(885,3,"It ______a beautiful house."),
(886,3,"I ______22 years old. (Negative)"),
(887,3,"It ______time to go to have dinner."),
(888,3,"I ______(like) watching series in the past"),
(889,3,"Juan Montalvo ______(write) many books."),
(890,3,"Plato ______(is) a Greek philosopher"),
(891,3,"Her favorite band ______(give) an excellent concert last month"),
(892,3,"He ______(play) with his friends when he was a child"),
(893,3,"Thomas ______(lose) his identity card."),
(894,3,"It ______(take) me a few hours to complete this task"),
(895,3,"The flu disease ______(break) out in 2019"),
(896,3,"Bernard ______(look) scared"),
(897,3,"Sophie ______(do) the test"),
(898,3,"______you like this show? (USE AFFIRMATIVE FORM)"),
(899,3,"______he love classical music? (USE AFFIRMATIVE FORM)"),
(900,3,"Who ______you speak in the school with? (USE AFFIRMATIVE FORM)"),
(901,3,"Stephanie ______smoke. (USE NEGATIVE FORM)"),
(902,3,"______she prepare the party? (USE AFFIRMATIVE FORM)"),
(903,3,"______she come from the vacation? (USE AFFIRMATIVE FORM)"),
(904,3,"______it have a nickname? (USE AFFIRMATIVE FORM)"),
(905,3,"______you work as a janitor? (USE AFFIRMATIVE FORM)"),
(906,3,"______Hilary ride a bike? (USE AFFIRMATIVE FORM)"),
(907,3,"______Luisa paint her hair (USE AFFIRMATIVE FORM)"),
(908,3,"They ______speak German (USE NEGATIVE FORM)"),
(909,3,"Mi conejo esta durmiendo. / ______rabbit is sleeping."),
(910,3,"Tu perro esta descansando. / ______dog is resting."),
(911,3,"Es mi horario. / It’s ______ schedule"),
(912,3,"Claudia lucirá sus botas nuevas. / Clau will wear ______new boots"),
(913,3,"Xavier vive con sus abuelos/ Javier lives with ______grandparents."),
(914,3,"Gloria aprende con su hijo/ Gloria learns with ______son."),
(915,3,"Cuéntame sobre tus metas. / Tell me about ______goals."),
(916,3,"¿Esos son tus hermanos? / Are those ______brothers?"),
(917,3,"Nuestra inversion está creciendo/ ______investment is growing."),
(918,3,"We ______very happy during my childhood"),
(919,3,"He ______sick in the school."),
(920,3,"We ______single."),
(921,3,"The concert ______very funny."),
(922,3,"My mother ______a nurse."),
(923,3,"The weather ______cloudy"),
(924,3,"Where ______she?"),
(925,3,"Edmundo ______asleep when we arrived."),
(926,3,"Rostro in English is ______"),
(927,3,"Cejas in English are ______"),
(928,3,"Cabello in English is ______"),
(929,3,"Pestañas in English are ______"),
(930,3,"Labios in English are ______"),
(931,3,"Lengua in English is ______"),
(932,3,"Mejillas in English are ______"),
(933,3,"Cuello in English is ______"),
(934,3,"Dientes in English are ______"),
(935,3,"Panadero in English is ______"),
(936,3,"Politico in English is ______"),
(937,3,"Químico in English is ______"),
(938,3,"Filósofo in English is ______"),
(939,3,"Modista in English is ______"),
(940,3,"Servidora Policial in English is ______"),
(941,3,"Cirujano in English is ______"),
(942,3,"Abogado in English is ______"),
(943,3,"Modelo in English is ______"),
(944,3,"We _____happy in his hotel."),
(1329,3,"Andrea _____ hungry."),


(945,3,"CHOOSE THE INCORRECT PART FROM THE FOLLOWING EXERCISES: How much(a) politicians(b) are(c) there in our(d) country?"),
(946,3,"CHOOSE THE INCORRECT PART FROM THE FOLLOWING EXERCISES: How many(a) towns(b) is(is) there in your(d) city?"),
(947,3,"CHOOSE THE INCORRECT PART FROM THE FOLLOWING EXERCISES: There is(a) a lot of(b) mice in(c) the old(d) houses."),
(948,3,"CHOOSE THE INCORRECT PART FROM THE FOLLOWING EXERCISES: There are(a) twelve tooth(b) in her little(c) mouth(d).");



INSERT INTO `questions` (`id`,`quizId`,`text`) VALUES

(949,3,"A tomato is a vegetable"),
(950,3,"The world is flat"),
(951,3,"A banana is a vegetable"),
(952,3,"Dolphins are fish"),
(953,3,"Whales are mammals"),
(954,3,"The Pacific Ocean is the largest ocean on Earth"),
(955,3,"The word “excellent” means the same as “terrible.”"),
(956,3,"The word “beautiful” is an adjective"),
(957,3,"The word “dog” is a verb"),
(958,3,"The word “honesty” is a noun"),
(959,3,"A synonym for “big” could be “small.”"),
(960,3,"The word “swimming” is a noun"),
(961,3,"An antonym for “rich” could be “poor.”"),
(962,3,"The word “quick” is a noun"),
(963,3,"Christmas is celebrated on December 25th"),
(964,3,"Valentine’s Day is celebrated on February 14th."),
(965,3,"Kangaroos live in Africa"),
(966,3,"Giraffes have short necks"),
(967,3,"Stars are made of cheese"),
(968,3,"The moon orbits the Earth"),

(969,3,"Do you like to swim or dance?"),
(970,3,"Which one is a countable noun?"),
(971,3,"Is there_____water in the glass?"),
(972,3,"I am going to school"),
(973,3,"Is your pen red?"),
(974,3,"March is the_____month of the year"),
(975,3,"I go to school _____ Monday_____7 o'clock"),
(976,3,"I_____a headache."),
(977,3,"I was born_____1993"),
(978,3,"_____fingers do you have?"),


(979,3,"Are you French?"),
(980,3,"Do you speak English?"),
(981,3,"This is _____apple."),
(982,3,"That girl is Sarah. _____is _____sister."),
(983,3,"I like to visit museums _____art galleries when I travel."),
(984,3,"Peter's house is bigger _____mine."),
(985,3,"_____book is this? It's Mike's"),
(986,3,"What time _____get up at weekends?"),
(987,3,"_____are my cousins, Jack and Ellen."),
(988,3,"Are _____?"),


-- Lenguaje

(989,4,"El ensayo argumentativo tiene como finalidadconvencer al lector sobre un punto de vista determinado"),
(990,4,"Los signos de puntuación sirven exclusivamente para decorar un texto"),
(991,4,"La polisemia ocurre cuando una palabra tiene varios significados relacionados entre sí"),
(992,4,"La homonimia se da cuando dos palabras tienen la misma escritura o pronunciación, pero diferentes significados"),
(993,4,"Un ditirambo es un poema de alabanza exagerada,originalmente relacionado con el culto a Dionisio"),
(994,4,"El texto expositivo busca persuadir al lector sobre un tema"),
(995,4,"La estructura de una página digital incluye encabezado, cuerpo y pie de página"),
(996,4,"En un texto argumentativo, los conectores lógicos son irrelevantes para su comprensión"),
(997,4,"El ensayo es un texto literario que combina información y opinión personal"),
(998,4,"La literatura épica narra hechos reales en su totalidad"),
(999,4,"La intertextualidad implica la relación de un texto con otros textos"),
(1000,4,"Un resumen consiste en reducir un texto a susideas principales con las mismas palabras del autor"),
(1001,4,"La crónica es un relato de hechos reales contados cronológicamente"),
(1002,4,"Los neologismos son palabras que se crean para nombrar conceptos nuevos"),
(1003,4,"El español de América es uniforme en todos los países de habla hispana"),
(1004,4,"Los prefijos y sufijos son morfemas que cambian el significado de las palabras"),
(1005,4,"Un texto narrativo tiene como característica principal la descripción de emociones"),
(1006,4,"La comunicación oral incluye elementos como el tono y la entonación"),
(1007,4,"Las variedades lingüísticas se clasifican endiatópicas, diastráticas y diafásicas"),
(1008,4,"El cómic es una forma de literatura escrita exclusivamente para niños"),
(1009,4,"Los textos publicitarios buscan persuadir alreceptor para que adquiera un producto o servicio"),
(1010,4,"El Modernismo literario se caracteriza por el rechazo a la estética tradicional"),
(1011,4,"La generación del 30 en Ecuador pertenece al movimiento de realismo social"),
(1012,4,"La reseña es un texto expositivo y valorativo que describe y opina sobre una obra"),
(1013,4,"El ensayo hispanoamericano es exclusivamente unaobra literaria de ficción"),
(1014,4,"Las falacias son argumentos válidos y lógicos"),
(1015,4,"Los textos académicos requieren rigor en la selección de fuentes"),
(1016,4,"La novela hispanoamericana del siglo XX se enfoca principalmente en temas mitológicos"),
(1017,4,"La diversidad lingüística enriquece el patrimonio cultural de una región"),
(1018,4,"El género dramático incluye obras escritas para ser representadas en escena"),
(1019,4,"Las figuras retóricas se utilizan exclusivamente en la poesía"),
(1020,4,"La lectura inferencial permite deducir información implícita en un texto"),
(1021,4,"El concepto de diglosia se refiere al uso de dos variedades de una lengua en diferentes ámbitos sociales"),
(1022,4,"Las normas APA son un sistema de citación para textos académicos"),
(1023,4,"La escritura en redes sociales debe cumplir con las mismas normas gramaticales que un texto formal"),
(1024,4,"El realismo social ecuatoriano critica las desigualdades sociales"),
(1025,4,"El subrayado es una técnica que permite identificar ideas principales en un texto"),
(1026,4,"Las oraciones simples tienen más de un sujeto y un predicado"),
(1027,4,"Las palabras homónimas tienen un origen etimológico común"),
(1028,4,"La lectura denotativa se centra en el significado literal de las palabras"),
(1029,4,"Un debate consiste en exponer ideas y refutarlas de manera respetuosa"),
(1030,4,"Los vicios del lenguaje como el pleonasmoenriquecen la expresión oral"),
(1031,4,"Las variedades lingüísticas diatópicas se refieren a las diferencias de lenguaje entre generaciones"),
(1032,4,"La narración en primera persona ofrece una visión subjetiva de los hechos"),
(1033,4,"La metáfora es una comparación directa entre dos elementos"),
(1034,4,"El comentario es un texto académico que explica yvalora otro texto"),
(1035,4,"La cohesión textual se logra con el uso adecuado de conectores y referencias"),
(1036,4,"El estilo directo implica que el narrador interpreta las palabras de los personajes"),
(1037,4,"El ensayo no requiere una estructura definida"),
(1038,4,"Las referencias bibliográficas son esenciales paradar crédito a las fuentes utilizadas"),
(1039,4,"La lectura connotativa permite analizar los significados implícitos en un texto"),
(1040,4,"Los textos digitales carecen de estructura definida en comparación con los impresos"),
(1041,4,"El tono en un texto refleja la actitud del autor hacia el tema tratado"),
(1042,4,"Los elementos paralingüísticos como el volumen y el ritmo afectan la comunicación oral"),
(1043,4,"Los textos académicos siempre son subjetivos"),
(1044,4,"La entrevista es un tipo de texto narrativo"),
(1045,4,"Los organizadores gráficos ayudan a la comprensión de un texto"),
(1046,4,"La hipérbole es una figura retórica que minimiza unaspecto para destacar otro"),
(1047,4,"El discurso argumentativo utiliza evidencias para sustentar sus ideas"),
(1048,4,"La ironía implica decir lo contrario de lo que realmente se piensa"),
(1049,4,"La coherencia textual es necesaria para que un texto sea comprensible"),
(1050,4,"Las variantes lingüísticas diastráticas están relacionadas con la geografía"),
(1051,4,"Un informe académico debe presentar datos verificables"),
(1052,4,"La novela realista busca representar la vida tal como es"),
(1053,4,"Los textos publicitarios no tienen intención persuasiva"),
(1054,4,"El uso de metáforas es exclusivo de la poesía"),
(1055,4,"Las reglas ortográficas son universales para todos los idiomas"),
(1056,4,"La generación del 27 fue un movimiento literario hispanoamericano"),
(1057,4,"Un monólogo interior refleja los pensamientos delpersonaje en forma directa"),
(1058,4,"Los elementos gráficos como viñetas y negritas mejoran la presentación de un texto"),
(1059,4,"La crítica literaria analiza y valora obras literarias"),
(1060,4,"Los textos periodísticos tienen como única función informar"),
(1061,4,"El texto descriptivo se enfoca en representar personas, lugares o cosas"),
(1062,4,"La tragedia es un subgénero literario dentro del drama"),
(1063,4,"Las palabras homófonas tienen igual pronunciación, pero distinto significado"),
(1064,4,"La voz pasiva se utiliza para destacar la acción enlugar del sujeto que la realiza"),
(1065,4,"El análisis literario se centra únicamente en el argumento de la obra"),
(1066,4,"La elipsis consiste en omitir elementos de una oración que se sobreentienden"),
(1067,4,"La novela picaresca se originó en la literatura francesa"),
(1068,4,"Los textos históricos relatan eventos pasados de forma ficticia"),
(1069,4,"La gramática prescriptiva describe el uso real de la lengua"),
(1070,4,"El realismo mágico combina elementos reales con fantásticos"),
(1071,4,"Un poema puede carecer de rima pero conservar suritmo"),
(1072,4,"La literatura precolombina incluye textos escritos antes de la llegada de los europeos"),
(1073,4,"Las jergas son variedades lingüísticas utilizadas en contextos especializados"),
(1074,4,"La fonética estudia el significado de las palabras"),
(1075,4,"Los géneros literarios se clasifican en lírico, épico y narrativo"),
(1076,4,"La puntuación no afecta el significado de un texto"),
(1077,4,"La sinestesia es una figura retórica que mezcla sensaciones de distintos sentidos"),
(1078,4,"El ensayo crítico evalúa las ideas de un texto con argumentos razonados"),
(1079,4,"El simbolismo literario es exclusivo de la poesía"),
(1080,4,"La literatura universal incluye obras representativas de distintas culturas y épocas"),
(1081,4,"Un epígrafe es un resumen al final de un texto"),
(1082,4,"La función apelativa del lenguaje busca convencer al receptor"),
(1083,4,"Las unidades mínimas de significado son los fonemas"),
(1084,4,"La novela policial se caracteriza por un enfoque en resolver un misterio"),
(1085,4,"La descripción subjetiva incluye la opinión personal del autor"),
(1086,4,"Los caligramas son un tipo de poesía visual"),
(1087,4,"La literatura infantil tiene como única finalidadentretener"),
(1088,4,"El discurso expositivo presenta información de manera clara y ordenada"),
(1089,4,"El texto argumentativo tiene como propósito principal persuadir al lector"),
(1090,4,"La cohesión textual depende exclusivamente deluso correcto de conectores"),
(1091,4,"Los textos narrativos incluyen personajes, un espacio y un tiempo definidos"),
(1092,4,"La función poética del lenguaje se centra en la estética del mensaje"),
(1093,4,"Los pronombres personales son invariables en todas las lenguas"),
(1094,4,"El análisis crítico literario se basa únicamente enla biografía del autor"),
(1095,4,"La contextualización es clave para comprender un texto histórico"),
(1096,4,"El género lírico siempre utiliza la primera persona como narrador"),
(1097,4,"El hiperbatón altera el orden lógico de las palabras en una oración"),
(1098,4,"La lectura analógica busca establecer comparaciones entre conceptos"),
(1099,4,"El género epistolar se caracteriza por emplear el formato de cartas"),
(1100,4,"Un texto publicitario utiliza recursos lingüísticos para persuadir"),
(1101,4,"La función referencial del lenguaje describeobjetos y eventos del mundo real"),
(1102,4,"La poesía moderna rechaza toda métrica tradicional"),
(1103,4,"Los mitos explican fenómenos naturales y culturales a través de relatos simbólicos"),
(1104,4,"La comunicación no verbal incluye gestos y expresiones faciales"),
(1105,4,"El narrador omnisciente conoce los pensamientos y sentimientos de todos los personajes"),
(1106,4,"El paralelismo es una figura retórica que consiste en la repetición de estructuras similares"),
(1107,4,"La literatura medieval en Europa se transmitía principalmente de forma escrita"),
(1108,4,"Los cuentos de hadas son ejemplos de narraciones orales tradicionales"),
(1109,4,"La novela de ciencia ficción anticipa avances tecnológicos y sus consecuencias"),
(1110,4,"Las variantes lingüísticas diatópicas están relacionadas con las diferencias geográficas"),
(1111,4,"Un texto descriptivo utiliza adjetivos para detallar características de personas o cosas"),
(1112,4,"Las leyendas son relatos que mezclan hechos históricos con elementos ficticios"),
(1113,4,"La función emotiva del lenguaje expresa sentimientos y emociones del emisor"),
(1114,4,"Las onomatopeyas son palabras que imitan sonidos de la realidad"),
(1115,4,"El verso libre carece de rima y métrica definida"),
(1116,4,"Los textos técnicos están destinados a especialistas en un área específica"),
(1117,4,"El oxímoron combina dos ideas opuestas en una misma expresión"),
(1118,4,"La literatura oral es anterior a la escritura"),
(1119,4,"Los caligramas son poemas que forman figuras visuales relacionadas con su contenido"),
(1120,4,"El análisis sintáctico estudia la función de las palabras en una oración"),
(1121,4,"La elisión es la omisión de sonidos o palabras en una oración"),
(1122,4,"La literatura fantástica mezcla elementos realescon elementos irreales o mágicos"),
(1123,4,"Los textos periodísticos incluyen noticias, editoriales y crónicas"),
(1124,4,"Las autobiografías narran la vida de otra persona desde un punto de vista externo"),
(1125,4,"La función conativa del lenguaje busca influir en el comportamiento del receptor"),
(1126,4,"La novela realista utiliza descripciones detalladas para representar la vida cotidiana"),
(1127,4,"La metonimia sustituye un término por otro relacionado por proximidad o asociación"),
(1128,4,"La epopeya es un subgénero narrativo que relata hazañas heroicas"),
(1129,4,"La escritura creativa se limita a los génerosliterarios"),
(1130,4,"Los textos expositivos presentan información de manera objetiva y clara"),
(1131,4,"Las parábolas son relatos breves que transmiten una enseñanza moral"),
(1132,4,"El haiku es una forma de poesía tradicionaljaponesa"),
(1133,4,"El género dramático utiliza diálogos para desarrollar su trama"),
(1134,4,"El intertexto conecta un texto con referencias a otros textos"),
(1135,4,"La literatura renacentista destaca la importancia de la religión en la vida cotidiana"),
(1136,4,"La ironía dramática ocurre cuando el lector sabealgo que los personajes desconocen"),
(1137,4,"Los textos instructivos indican los pasos para realizar una tarea o proceso"),
(1138,4,"La sátira utiliza el humor para criticar aspectos de la sociedad"),
(1139,4,"El diálogo es un recurso exclusivo del género narrativo"),
(1140,4,"Los textos históricos deben basarse únicamente en fuentes primarias"),
(1141,4,"La tragedia griega combina elementos cómicos y trágicos en sus obras"),
(1142,4,"El narrador en segunda persona dirige la narración al lector"),
(1143,4,"El soliloquio es un monólogo dirigido hacia elpúblico"),
(1144,4,"La literatura barroca se caracteriza por el uso de complejas figuras retóricas"),
(1145,4,"La poesía épica se enfoca exclusivamente en temas religiosos"),
(1146,4,"El realismo mágico busca explicar fenómenos sobrenaturales de manera racional"),
(1147,4,"Los textos descriptivos son subjetivos por naturaleza"),
(1148,4,"La literatura infantil incluye obras que desarrollan valores educativos"),
(1149,4,"El ensayo reflexivo combina narración y argumentación"),
(1150,4,"Los dialectos son variedades de una lenguahablada en regiones específicas"),
(1151,4,"La prosa poética utiliza elementos líricos en un formato narrativo"),
(1152,4,"Los textos satíricos siempre buscan ofender al lector"),
(1153,4,"La novela contemporánea experimenta con nuevasestructuras narrativas"),
(1154,4,"Las palabras agudas llevan tilde si terminan en vocal, n o s"),
(1155,4,"La crónica periodística combina información con elementos literarios"),
(1156,4,"Los aforismos son frases breves que contienen una reflexión profunda"),
(1157,4,"La literatura oral carece de valor histórico ycultural"),
(1158,4,"Los textos híbridos combinan características de diferentes géneros"),


INSERT INTO `questions` (`id`,`quizId`,`text`) VALUES


(1159,4,'¿Cuál es la función principal del texto expositivo?'),
(1160,4,'¿Qué recurso literario se emplea en la expresión "el rugido del viento"?'),
(1161,4,'¿Cuál de las siguientes opciones es un ejemplo de homonimia?'),
(1162,4,'¿Qué distingue a un texto argumentativo?'),
(1163,4,'¿Qué caracteriza a un narrador omnisciente?'),
(1164,4,'¿Cuál es el propósito principal de una fábula?'),
(1165,4,'¿Qué figura literaria compara elementos usando "como"?'),
(1166,4,'¿Cuál es un ejemplo de literatura renacentista?'),
(1167,4,'¿Qué tipo de texto tiene como función principal persuadir al receptor?'),
(1168,4,'¿Qué tipo de lenguaje predomina en la poesía?'),
(1169,4,'¿Qué distingue a un cuento de una novela?'),
(1170,4,'¿Qué recurso literario está presente en la frase "Es tan lento como una tortuga"?'),
(1171,4,'¿Qué es un caligrama?'),
(1172,4,'¿Qué subgénero pertenece al género dramático?'),
(1173,4,'¿Qué es una metáfora?'),
(1174,4,'¿Qué tipo de narrador utiliza "yo" para relatar la historia?'),
(1175,4,'¿Qué figura retórica se usa en la frase "Sus lágrimas eran ríos"?'),
(1176,4,'¿Qué caracteriza a los textos informativos?'),
(1177,4,'¿Qué figura retórica utiliza ideas opuestas en una misma frase?'),
(1178,4,'¿Qué subgénero literario incluye cuentos de fantasía?'),
(1179,4,'¿Qué tipo de texto tiene como objetivo principal narrar hechos reales o ficticios?'),
(1180,4,'¿Qué recurso literario está presente en la frase "El tiempo vuela"?'),
(1181,4,'¿Qué caracteriza a una novela?'),
(1182,4,'¿Qué figura retórica se usa para exagerar una idea o situación?'),
(1183,4,'¿Cuál es una característica de los textos descriptivos?'),
(1184,4,'¿Qué tipo de texto busca influir en el receptor utilizando recursos lingüísticos?'),
(1185,4,'¿Qué elemento es esencial en un texto argumentativo?'),
(1186,4,'¿Qué función del lenguaje predomina en un mensaje publicitario?'),
(1187,4,'¿Qué recurso literario está presente en "Silencio ensordecedor"?'),
(1188,4,'¿Qué caracteriza al subgénero de la epopeya?'),
(1189,4,'¿Qué elemento distingue a un poema lírico?'),
(1190,4,'¿Qué subgénero pertenece al género narrativo?'),
(1191,4,'¿Qué figura retórica se utiliza al decir "Eres el sol que ilumina mi vida"?'),
(1192,4,'¿Qué distingue al texto expositivo?'),
(1193,4,'¿Qué subgénero literario combina ficción con elementos mágicos?'),
(1194,4,'¿Qué tipo de texto combina elementos de análisis e interpretación crítica?'),
(1195,4,'¿Qué función del lenguaje se utiliza para expresar sentimientos?'),
(1196,4,'¿Qué característica tiene el narrador en segunda persona?'),
(1197,4,'¿Qué recurso literario utiliza "El silencio gritaba en la habitación"?'),
(1198,4,'¿Qué función del lenguaje se enfoca en la estructura del mensaje?'),
(1199,4,'¿Qué distingue a una biografía?'),
(1200,4,'¿Qué subgénero literario pertenece al género lírico?'),
(1201,4,'¿Qué figura retórica se usa al decir "Era un gigante entre los hombres"?'),
(1202,4,'¿Qué característica define al género dramático?'),
(1203,4,'¿Qué diferencia a una leyenda de un mito?'),
(1204,4,'¿Qué recurso literario compara sin usar "como"?'),
(1205,4,'¿Qué caracteriza a un texto periodístico?'),
(1206,4,'¿Qué función del lenguaje predomina en una noticia?'),
(1207,4,'¿Qué es un monólogo?'),
(1208,4,'¿Qué figura literaria mezcla ideas contradictorias en una misma frase?'),
(1209,4,'¿Qué subgénero literario narra hechos reales y utiliza un enfoque cronológico?'),
(1210,4,'¿Qué tipo de texto busca enseñar o educar al lector?'),
(1211,4,'¿Qué caracteriza a un ensayo literario?'),
(1212,4,'¿Qué subgénero pertenece al género narrativo?'),
(1213,4,'¿Qué figura retórica consiste en exagerar para enfatizar una idea?'),
(1214,4,'¿Qué caracteriza al realismo literario?'),
(1215,4,'¿Qué función del lenguaje se utiliza en una conversación cotidiana?'),
(1216,4,'¿Qué distingue al narrador testigo?'),
(1217,4,'¿Qué recurso literario está presente en "Una dulce amargura inundó su corazón"?'),
(1218,4,'¿Qué caracteriza a una obra de teatro?'),
(1219,4,'¿Qué tipo de texto busca detallar las características de un objeto o persona?'),
(1220,4,'¿Qué figura retórica combina elementos sensoriales diferentes?'),
(1221,4,'¿Qué distingue a un poema épico?'),
(1222,4,'¿Qué función del lenguaje predomina en los mensajes de alerta?'),
(1223,4,'¿Qué caracteriza al texto lírico?'),
(1224,4,'¿Qué subgénero literario incluye reflexiones filosóficas o morales?'),
(1225,4,'¿Qué figura literaria se utiliza al decir "Las estrellas me guiaron en la noche"?'),
(1226,4,'¿Qué tipo de narrador relata la historia desde una perspectiva externa sin conocer pensamientos de los personajes?'),
(1227,4,'¿Qué recurso literario está presente en "Eres tan fuerte como un roble"?'),
(1228,4,'¿Qué caracteriza al género de la fábula?'),
(1229,4,'¿Qué función del lenguaje se utiliza en las instrucciones de un manual?'),
(1230,4,'¿Qué distingue a la novela realista?'),
(1231,4,'¿Qué subgénero literario pertenece al género narrativo?'),
(1232,4,'¿Qué figura retórica está presente en "El hielo ardía en sus manos"?'),
(1233,4,'¿Qué caracteriza a los textos científicos?'),
(1234,4,'¿Qué función del lenguaje predomina en una conversación telefónica casual?'),
(1235,4,'¿Qué elemento distingue a una tragedia griega?'),
(1236,4,'¿Qué tipo de texto presenta información ordenada y explicada claramente?'),
(1237,4,'¿Qué figura retórica está presente en "El reloj corría más rápido que nunca"?'),
(1238,4,'¿Qué caracteriza a un ensayo filosófico?'),
(1239,4,'¿Qué subgénero literario se centra en relatar historias breves con pocos personajes?'),
(1240,4,'¿Qué figura retórica combina elementos contradictorios?'),
(1241,4,'¿Qué función del lenguaje predomina en los mensajes informativos?'),
(1242,4,'¿Qué distingue al género de la tragedia?'),
(1243,4,'¿Qué recurso literario se utiliza al decir "Una luz de esperanza iluminó mi camino"?'),
(1244,4,'¿Qué tipo de narrador es un personaje secundario que observa la historia?'),
(1245,4,'¿Qué figura literaria exagera intencionalmente una característica?'),
(1246,4,'¿Qué característica define a los textos académicos?'),
(1247,4,'¿Qué distingue a los textos descriptivos?'),
(1248,4,'¿Qué subgénero literario combina realidad con elementos mágicos?'),
(1249,4,'¿Qué función del lenguaje se utiliza en un poema?'),
(1250,4,'¿Qué recurso literario compara utilizando "como"?'),
(1251,4,'¿Qué tipo de narrador conoce los pensamientos de todos los personajes?'),
(1252,4,'¿Qué subgénero pertenece al género lírico?'),
(1253,4,'¿Qué función del lenguaje se utiliza al persuadir al lector?'),
(1254,4,'¿Qué recurso literario está presente en "El rugido del león era música para sus oídos"?'),
(1255,4,'¿Qué recurso literario utiliza elementos opuestos en una misma frase?'),
(1256,4,'¿Qué figura literaria mezcla sensaciones de diferentes sentidos?'),
(1257,4,'¿Qué tipo de texto busca enseñar al lector?'),
(1258,4,'¿Qué función del lenguaje predomina en un discurso político?'),
(1259,4,'¿Qué recurso literario está presente en "La ciudad dormía bajo el manto de la noche"?'),
(1260,4,'¿Qué caracteriza a un poema lírico?'),
(1261,4,'¿Qué distingue a una autobiografía?'),
(1262,4,'¿Qué figura retórica exagera para destacar un punto?'),
(1263,4,'¿Qué tipo de narrador no participa en la historia, pero conoce todos los detalles?'),
(1264,4,'¿Qué caracteriza a una tragedia?'),
(1265,4,'¿Qué figura literaria se utiliza en "El mundo es un pañuelo"?'),
(1266,4,'¿Qué caracteriza a un texto argumentativo?'),
(1267,4,'¿Qué subgénero literario es un relato breve con enseñanza moral?'),
(1268,4,'¿Qué figura retórica está presente en "La risa resonaba como campanas"?'),
(1269,4,'¿Qué distingue al narrador omnisciente?'),
(1270,4,'¿Qué recurso literario exagera para destacar una característica?'),
(1271,4,'¿Qué tipo de texto combina elementos poéticos con narrativa?'),
(1272,4,'¿Qué característica define a una epopeya?'),
(1273,4,'¿Qué función del lenguaje predomina en un poema lírico?'),
(1274,4,'¿Qué figura retórica mezcla ideas opuestas en una frase?'),
(1275,4,'¿Qué distingue al género de la crónica?'),
(1276,4,'¿Qué figura literaria combina sentidos distintos, como "colores chillones"?'),
(1277,4,'¿Qué función del lenguaje predomina en los manuales de instrucciones?'),
(1278,4,'¿Qué subgénero literario utiliza personajes antropomórficos con moraleja?'),
(1279,4,'¿Qué distingue al género lírico?'),
(1280,4,'¿Qué recurso literario está presente en "El corazón del bosque latía fuerte"?'),
(1281,4,'¿Qué caracteriza a los textos narrativos?'),
(1282,4,'¿Qué figura retórica exagera intencionalmente una situación?'),
(1283,4,'¿Qué tipo de narrador relata eventos sin conocer pensamientos de los personajes?'),
(1284,4,'¿Qué subgénero combina elementos mágicos con realidad?'),
(1285,4,'¿Qué función del lenguaje predomina en los eslóganes publicitarios?'),
(1286,4,'¿Qué distingue a un ensayo literario?'),
(1287,4,'¿Qué recurso literario se usa al decir "El tiempo volaba"?'),
(1288,4,'¿Qué tipo de narrador está involucrado directamente en los eventos?'),
(1289,4,'¿Qué figura retórica utiliza "Eres un ángel"?'),
(1290,4,'¿Qué función del lenguaje predomina en las conversaciones casuales?'),
(1291,4,'¿Qué caracteriza a una tragedia griega?'),
(1292,4,'¿Qué recurso literario está presente en "Una cascada de lágrimas cayó de sus ojos"?'),
(1293,4,'¿Qué figura literaria se utiliza en "El mundo es un pañuelo"?'),
(1294,4,'¿Qué caracteriza a un texto argumentativo?'),
(1295,4,'¿Qué subgénero literario es un relato breve con enseñanza moral?'),
(1296,4,'¿Qué figura retórica está presente en "La risa resonaba como campanas"?'),
(1297,4,'¿Qué distingue al narrador omnisciente?'),
(1298,4,'¿Qué recurso literario exagera para destacar una característica?'),
(1299,4,'¿Qué tipo de texto combina elementos poéticos con narrativa?'),
(1300,4,'¿Qué característica define a una epopeya?'),
(1301,4,'¿Qué función del lenguaje predomina en un poema lírico?'),
(1302,4,'¿Qué figura retórica mezcla ideas opuestas en una frase?'),
(1303,4,'¿Qué distingue al género de la crónica?'),
(1304,4,'¿Qué subgénero pertenece al género dramático?'),
(1305,4,'¿Qué figura literaria combina sentidos distintos, como "colores chillones"?'),
(1306,4,'¿Qué función del lenguaje predomina en los manuales de instrucciones?'),
(1307,4,'¿Qué subgénero literario utiliza personajes antropomórficos con moraleja?'),
(1308,4,'¿Qué distingue al género lírico?'),
(1309,4,'¿Qué recurso literario está presente en "El corazón del bosque latía fuerte"?'),
(1310,4,'¿Qué caracteriza a los textos narrativos?'),
(1311,4,'¿Qué figura retórica exagera intencionalmente una situación?'),
(1312,4,'¿Qué tipo de narrador relata eventos sin conocer pensamientos de los personajes?'),
(1313,4,'¿Qué subgénero combina elementos mágicos con realidad?'),
(1314,4,'¿Qué función del lenguaje predomina en los eslóganes publicitarios?'),
(1315,4,'¿Qué distingue a un ensayo literario?'),
(1316,4,'¿Qué recurso literario se usa al decir "El tiempo volaba"?'),
(1317,4,'¿Qué caracteriza a una novela?'),
(1318,4,'¿Qué tipo de narrador está involucrado directamente en los eventos?'),
(1319,4,'¿Qué figura retórica utiliza "Eres un ángel"?'),
(1320,4,'¿Qué función del lenguaje predomina en las conversaciones casuales?'),
(1321,4,'¿Qué caracteriza a una tragedia griega?'),
(1322,4,'¿Qué recurso literario está presente en "Una cascada de lágrimas cayó de sus ojos"?'),
(1323,4,'¿Qué tipo de narrador utiliza "tú" para dirigirse al lector como si fuera el protagonista?'),
(1324,4,'¿Qué función del lenguaje se utiliza al expresar sentimientos y emociones?'),
(1325,4,'¿Qué distingue a la literatura barroca?'),
(1326,4,'¿Qué figura retórica está presente en "La vida es un sueño"?'),
(1327,4,'¿Qué tipo de texto combina elementos narrativos con reflexión personal?'),
(1328,4,'¿Qué subgénero literario incluye la expresión subjetiva y emocional del autor?'),


